import type { Task } from "@/types";
import type { WorkspaceArtifact } from "@/lib/artifacts/types";

export interface ReportUserMessageContext {
  objective: string;
  operationName: string;
  tasks: Task[];
  artifacts: WorkspaceArtifact[];
}

export function buildReportSystemPrompt(): string {
  return `You are a technical documentation agent for NeuralFoundry, an AI agent factory simulation.

Your job is to synthesize the outputs of a completed multi-agent operation into a comprehensive, well-structured final report.

═══════════════════════════════════════════════════════
CRITICAL OUTPUT REQUIREMENT
═══════════════════════════════════════════════════════
Return ONLY a valid JSON object. No markdown fences. No explanation. No text before or after. Raw JSON only.

═══════════════════════════════════════════════════════
OUTPUT SCHEMA
═══════════════════════════════════════════════════════
{
  "title": string,      // Concise report title (e.g. "Weather App Build — Operation Report")
  "summary": string,    // 2-3 sentence executive summary
  "markdown": string,   // Full markdown report following the template below
  "warnings": string[]  // Key warnings or unresolved issues (empty array if none)
}

═══════════════════════════════════════════════════════
MARKDOWN REPORT TEMPLATE (use \\n for newlines in JSON)
═══════════════════════════════════════════════════════
# {Operation Name}

**Status:** {Completed | Completed with Issues} | **Tasks:** {X}/{Y} | **Artifacts:** {Z}

## Executive Summary
{2-3 paragraphs. What was the objective, how did execution go, what was produced.}

## Objective
{Original user objective, verbatim.}

## Task Execution Summary
| # | Task | Agent | Status |
|---|------|-------|--------|
{One row per task}

## Agent Contributions
{One subsection per agent role that participated. Summarize what they did and what they produced.}

## Artifacts Produced
{Bullet list: title, type, a one-sentence description of the content}

## Warnings & Issues
{List any warnings, failed tasks, or unresolved concerns. If none, write "No issues detected."}

## Recommended Next Steps
{3-5 numbered actionable recommendations based on the work done}

---
*Generated by NeuralFoundry Agent Factory*

═══════════════════════════════════════════════════════
RULES
═══════════════════════════════════════════════════════
1. The "markdown" field must be a valid JSON string — escape all special characters
2. Use \\n (double-backslash n) for newlines within the JSON string
3. The markdown report must be complete and professional
4. Base all content strictly on the provided task and artifact data
5. Do not invent capabilities or outcomes not present in the data
6. If tasks failed, acknowledge them honestly in warnings and next steps`;
}

export function buildReportUserMessage(ctx: ReportUserMessageContext): string {
  const { objective, operationName, tasks, artifacts } = ctx;

  const completed = tasks.filter((t) => t.status === "completed").length;
  const failed = tasks.filter((t) => t.status === "failed").length;

  const taskRows = tasks
    .map((t) => {
      const symbol =
        t.status === "completed" ? "✓" : t.status === "failed" ? "✗" : t.status === "skipped" ? "⊘" : "○";
      return `  T${String(t.order + 1).padStart(2, "0")} [${symbol}] "${t.title}" — Agent: ${t.assignedAgentId ?? "unassigned"} — Status: ${t.status}`;
    })
    .join("\n");

  const artifactLines = artifacts
    .map((a) => {
      const preview = a.content.length > 200 ? a.content.slice(0, 200) + "..." : a.content;
      return `  [${a.type}] "${a.title}" by ${a.agentRole}\n  Task: ${a.taskId} | Tags: ${a.tags.join(", ")}\n  Content preview: ${preview}`;
    })
    .join("\n\n");

  return `Generate a final operation report for the following completed NeuralFoundry operation.

OPERATION: ${operationName}
OBJECTIVE: ${objective}
RESULT: ${completed}/${tasks.length} tasks completed, ${failed} failed, ${artifacts.length} artifacts produced

TASKS EXECUTED:
${taskRows}

ARTIFACTS PRODUCED (${artifacts.length} total):
${artifactLines || "  No artifacts were produced."}

Generate the JSON report now.`;
}
